### ISSUE TITLE
tilers_tools python issue

### ISSUE THREAD

**Issue by bvandre** [jlmcgraw/aviationCharts#8]
Unfortunately when running this script I get to a point where I run into an issue with running the tilers tools.  When attempting to tile the first warpedRaster i get the following error.  Any help with this issue would be appreciated.

 > --------Tiling Albuquerque_SEC------------
 Zoom levels are 0,1,2,3,4,5,6,7,8,9,10,11
 INFO:root: /files/5_warpedRasters/sectional/Albuquerque_SEC.tif -> /files/6_tiles/Albuquerque_SEC.tms
 Traceback (most recent call last):
   File "./tilers_tools/gdal_tiler.py", line 181, in <module>
     main(sys.argv)
   File "./tilers_tools/gdal_tiler.py", line 175, in main
     parallel_map(process_src, flatten(res))
   File "/scripts/tilers_tools/tiler_functions.py", line 98, in parallel_map
     return map(func, iterable)
   File "./tilers_tools/gdal_tiler.py", line 66, in process_src
     prm.walk_pyramid()
   File "/scripts/tilers_tools/tiler_backend.py", line 675, in walk_pyramid
     self.make_raster(self.max_zoom)
   File "/scripts/tilers_tools/tiler_backend.py", line 531, in make_raster
     ok, src_igeotr = gdal.InvGeoTransform(src_geotr)
 ValueError: too many values to unpack

**Comment by bvandre** [comment]
It looks like the issue i had was i was using gdal 2.x.

**Comment by dajester2013** [comment]
What version do you need?
Edit - found in the readme - its 1.10.
